### ISSUE TITLE
The install_enclave_dependencies.sh only allows Ubuntu 20.04

### ISSUE THREAD

**Issue by stevenbravo1410** [PufferFinance/coral#23]
This can be easily fixed  changing 

if [ "$os_name" != "Ubuntu" ] || [ "$os_version" **!=** "20.04" ]; then
    log_error "**This script requires Ubuntu 20.04 to run."**

to:

if [ "$os_name" != "Ubuntu" ] || [ "$os_version" **>=** "20.04" ]; then
    log_error **"This script requires Ubuntu 20.04 or greater to run."**

**Comment by JasonVranek** [comment]
The enclave requires ubuntu 20.04 only
